steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'VCS_REF=$COMMIT_SHA', '-t', 'gcr.io/text-summarizer-bert/textify:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/text-summarizer-bert/textify:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'text-summarizer-bert',
      '--image', 'gcr.io/text-summarizer-bert/textify:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'europe-west1',
      '--allow-unauthenticated',
      '--set-env-vars', 'TEXTIFY_REQUIRE_ACCESS_CODE=1',
      '--set-secrets', 'TEXTIFY_ACCESS_CODE=textify-access-code:latest,OPENAI_API_KEY=textify-openai-api-key:latest'
    ]

images:
  - 'gcr.io/text-summarizer-bert/textify:$COMMIT_SHA'

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
